repos:
  # cspell (spelling for identifiers, filenames, comments)
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.13.0   # use a stable tag
    hooks:
      - id: cspell
        args: ["--no-progress", "--config", "cspell.config.json"]

  # cargo fmt (formatting check)
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'source ~/.cargo/env && cargo fmt -- --check'
        language: system
        types: [rust]
        pass_filenames: false

  # cargo clippy (linting)
  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        entry: bash -c 'source ~/.cargo/env && cargo clippy -- -D warnings'
        language: system
        types: [rust]
        pass_filenames: false
