name: Docs (gos → GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write        # needed for Pages deploy
  id-token: write     # needed for OIDC auth

concurrency:
  group: pages
  cancel-in-progress: true

# .github/workflows/docs.yml (snippet)
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      # NEW: install protoc so prost-build can run
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Build docs for gos only (no deps)
        env:
          RUSTDOCFLAGS: "-Dwarnings --cfg docsrs"
        run: |
          cargo doc --no-deps --all-features --package gos
          mkdir -p public
          cp -r target/doc/* public/
          cat > public/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=gos/">
          <title>gos docs</title>
          <p>Redirecting to <a href="gos/">gos/</a>…</p>
          HTML

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with: { path: public }
  deploy:
    needs: build-and-deploy-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
